apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
 name: pyflink-split-measures
spec:
 image: pyflink-tfm-split-measures:1.0 
 flinkVersion: v1_18
 flinkConfiguration:
   taskmanager.numberOfTaskSlots: "1"
 serviceAccount: flink
 jobManager:
   resource:
     memory: "2048m"
     cpu: 1
 taskManager:
    replicas: 1
    resource:
     memory: "2048m"
     cpu: 1
 job:
   jarURI: local:///opt/flink/opt/flink-python-1.18.0.jar
   entryClass: "org.apache.flink.client.python.PythonDriver"
   args: ["-pyclientexec", "/usr/bin/python3", "-py", "/opt/flink/usrlib/flink-split-measures.py"]
   parallelism: 1
   upgradeMode: stateless
