apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: pyflink-split-measures
spec:
  image: pyflink-tfm-split-measures:1.1
  flinkVersion: v1_18
  flinkConfiguration:
    askmanager.numberOfTaskSlots: "1"
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    metrics.reporter.prom.port: 9250-9260
    metrics.reporters: prom
    taskmanager.network.detailed-metrics: "true"

  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1

  taskManager:        
    replicas: 1
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/opt/flink-python-1.18.0.jar
    entryClass: "org.apache.flink.client.python.PythonDriver"
    args: ["-pyclientexec", "/usr/bin/python3", "-py", "/opt/flink/usrlib/flink-split-measures.py"]
    parallelism: 1
    upgradeMode: stateless
