{
 "title": "noise LAeq",
 "time": { "from": "2024-12-14T23:00:00.000Z", "to": "2024-12-15T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "Country",
    "label": "country",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"predictions\",\n  tag: \"country\",\n    predicate: (r) => r._measurement == \"noise_LAeq\"\n)\n"
    }
   },
   {
    "name": "Location",
    "label": "Location",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"predictions\",\n  tag: \"location\",\n  predicate: (r) => r._measurement == \"noise_LAeq\" and r[\"country\"] == \"${Country}\"\n)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 min noise LAeq",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBa" } },
   "targets": [
    {
     "query": "from(bucket: \"Raw data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  // Usa el rango de tiempo definido\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise_LAeq\")  // Filtrar la medición\n  |> filter(fn: (r) => r[\"_field\"] == \"noise_LAeq\")  // Filtrar el campo de temperatura\n  |> group(columns: [\"_measurement\", \"_field\", \"country\", \"location\"]) \n  |> aggregateWindow(every: 30d, fn: mean, createEmpty: false)  // Agrupar en ventanas de 10 minutos\n  |> group(columns: [\"_measurement\"]) // Elimina agrupaciones previas (para trabajar globalmente)\n  |> sort(columns: [\"_value\"], desc: false)  // Ordenar los datos por valor de temperatura en orden descendente\n  |> limit(n: 10)  // Tomar los 10 valores más altos globalmente\n  |> rename(columns: {_value: \"noise_LAeq\", location: \"Location\", country: \"Country\", _time: \"Time\"})  // Cambiar nombres de columnas\n  |> keep(columns: [\"noise_LAeq\", \"Country\", \"Location\"])  // Mantén solo las columnas relevantes\n"
    }
   ]
  },
  {
   "title": "Top 10 max noise LAeq",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBa" } },
   "targets": [
    {
     "query": "from(bucket: \"Raw data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  // Usa el rango de tiempo definido\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise_LAeq\")  // Filtrar la medición\n  |> filter(fn: (r) => r[\"_field\"] == \"noise_LAeq\")  // Filtrar el campo de temperatura\n  |> group(columns: [\"_measurement\", \"_field\", \"country\", \"location\"]) \n  |> aggregateWindow(every: 30d, fn: mean, createEmpty: false)  // Agrupar en ventanas de 10 minutos\n  |> group(columns: [\"_measurement\"]) // Elimina agrupaciones previas (para trabajar globalmente)\n  |> sort(columns: [\"_value\"], desc: true)  // Ordenar los datos por valor de temperatura en orden descendente\n  |> top(n: 10)  // Tomar los 10 valores más altos globalmente\n  |> rename(columns: {_value: \"noise_LAeq\", location: \"Location\", country: \"Country\", _time: \"Time\"})  // Cambiar nombres de columnas\n  |> keep(columns: [\"noise_LAeq\", \"Country\", \"Location\"])  // Mantén solo las columnas relevantes\n"
    }
   ]
  },
  {
   "title": "Real and predicted values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dBa" } },
   "targets": [
    {
     "query": "from(bucket: \"Raw data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"noise_LAeq\")\n  |> filter(fn: (r) => r._field == \"noise_LAeq\")\n  |> filter(fn: (r) => r[\"country\"] == \"${Country}\")\n  |> filter(fn: (r) => r[\"location\"] == \"${Location}\")\n  |> group(columns: [\"_measurement\", \"_field\", \"country\", \"location\"])\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\n  |> rename(columns: {_value: \"Temperatura Promedio\"})\n  |> yield(name: \"mean\")\n"
    },
    {
     "query": "from(bucket: \"predictions\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise_LAeq\")\n  |> filter(fn: (r) => r[\"_field\"] == \"noise_LAeq\")\n  |> filter(fn: (r) => r[\"country\"] == \"${Country}\")\n  |> filter(fn: (r) => r[\"location\"] == \"${Location}\")\n  |> group(columns: [\"_measurement\", \"_field\", \"country\", \"location\"])\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false) \n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "World map noise LAeq",
   "type": "geomap",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dBa" } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"Raw data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"noise_LAeq\")\n  |> filter(fn: (r) => r._field == \"latitude\" or r._field == \"longitude\" or r._field == \"noise_LAeq\")\n  |> group(columns: [\"_measurement\", \"_field\", \"country\", \"location\"])\n  |> aggregateWindow(every: 30d, fn: mean, createEmpty: false) \n  |> schema.fieldsAsCols()\n  |> group()\n  |> sort(columns: [\"_time\"])"
    }
   ]
  }
 ]
}