{
 "title": "PM10",
 "time": { "from": "2024-12-15T01:43:04.045Z", "to": "2024-12-15T02:30:17.675Z" },
 "templating": {
  "list": [
   {
    "name": "Country",
    "label": "country",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"predictions\",\n  tag: \"country\",\n    predicate: (r) => r._measurement == \"P1\"\n)\n"
    }
   },
   {
    "name": "Location",
    "label": "Location",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"predictions\",\n  tag: \"location\",\n  predicate: (r) => r._measurement == \"P1\" and r[\"country\"] == \"${Country}\"\n)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 min PM10",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µg/m^3" } },
   "targets": [
    {
     "query": "from(bucket: \"Raw data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  // Usa el rango de tiempo definido\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")  // Filtrar la medición\n  |> filter(fn: (r) => r[\"_field\"] == \"P1\")  // Filtrar el campo de temperatura\n  |> group(columns: [\"_measurement\", \"_field\", \"country\", \"location\"]) \n  |> aggregateWindow(every: 30d, fn: mean, createEmpty: false)  // Agrupar en ventanas de 10 minutos\n  |> group(columns: [\"_measurement\"]) // Elimina agrupaciones previas (para trabajar globalmente)\n  |> sort(columns: [\"_value\"], desc: false)  // Ordenar los datos por valor de temperatura en orden descendente\n  |> limit(n: 10)  // Tomar los 10 valores más altos globalmente\n  |> rename(columns: {_value: \"P1\", location: \"Location\", country: \"Country\", _time: \"Time\"})  // Cambiar nombres de columnas\n  |> keep(columns: [\"P1\", \"Country\", \"Location\"])  // Mantén solo las columnas relevantes\n"
    }
   ]
  },
  {
   "title": "Top 10 max PM10",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µg/m^3" } },
   "targets": [
    {
     "query": "from(bucket: \"Raw data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  // Usa el rango de tiempo definido\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")  // Filtrar la medición\n  |> filter(fn: (r) => r[\"_field\"] == \"P1\")  // Filtrar el campo de temperatura\n  |> group(columns: [\"_measurement\", \"_field\", \"country\", \"location\"]) \n  |> aggregateWindow(every: 30d, fn: mean, createEmpty: false)  // Agrupar en ventanas de 10 minutos\n  |> group(columns: [\"_measurement\"]) // Elimina agrupaciones previas (para trabajar globalmente)\n  |> sort(columns: [\"_value\"], desc: true)  // Ordenar los datos por valor de temperatura en orden descendente\n  |> top(n: 10)  // Tomar los 10 valores más altos globalmente\n  |> rename(columns: {_value: \"P1\", location: \"Location\", country: \"Country\", _time: \"Time\"})  // Cambiar nombres de columnas\n  |> keep(columns: [\"P1\", \"Country\", \"Location\"])  // Mantén solo las columnas relevantes\n"
    }
   ]
  },
  {
   "title": "Real and predicted values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µg/m^3" } },
   "targets": [
    {
     "query": "from(bucket: \"Raw data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"P1\")\n  |> filter(fn: (r) => r._field == \"P1\")\n  |> filter(fn: (r) => r[\"country\"] == \"${Country}\")\n  |> filter(fn: (r) => r[\"location\"] == \"${Location}\")\n  |> group(columns: [\"_measurement\", \"_field\", \"country\", \"location\"])\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\n  |> rename(columns: {_value: \"Temperatura Promedio\"})\n  |> yield(name: \"mean\")\n"
    },
    {
     "query": "from(bucket: \"predictions\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"P1\")\n  |> filter(fn: (r) => r[\"country\"] == \"${Country}\")\n  |> filter(fn: (r) => r[\"location\"] == \"${Location}\")\n  |> group(columns: [\"_measurement\", \"_field\", \"country\", \"location\"])\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false) \n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "World map P1s",
   "type": "geomap",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µg/m^3" } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"Raw data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"P1\")\n  |> filter(fn: (r) => r._field == \"latitude\" or r._field == \"longitude\" or r._field == \"P1\")\n  |> group(columns: [\"_measurement\", \"_field\", \"country\", \"location\"])\n  |> aggregateWindow(every: 30d, fn: mean, createEmpty: false) \n  |> schema.fieldsAsCols()\n  |> group()\n  |> sort(columns: [\"_time\"])"
    }
   ]
  }
 ]
}